version: '3.9'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:15.4-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  backend:
    image: foodgram_backend
    build: ../backend
    env_file: .env
    volumes:
      - media:/app/media
      - static:/app/static
    restart: always
    depends_on:
      - db
  frontend:
    image: foodgram_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build
  nginx:
    image: nginx:1.25.2-alpine-slim
    env_file: .env
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html
      - ../docs/:/usr/share/nginx/html/api/docs
      - media:/app/media
      - static:/usr/share/nginx/html/static/static
    restart: always
    depends_on:
      - backend
      - frontend